---
title: Novel
timezone: UTC
collections:
  branded:
    title: Branded
    output: false
  editorial:
    title: Editorial
    output: false
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: editorial
    values:
      image:
      client:
      logo:
      episodes:
      run-time:
      listen:
      link:
      is-highlight: false
      has-reviews: false
      reviews:
        - cite:
          is-five-star:
          is-four-star:
          link:
      has-awards: false
      awards:
        - award:
          link:
  - scope:
      path: ""
      type: branded
    values:
      image:
      client:
      logo:
      episodes:
      run-time:
      listen:
      link:
      is-highlight: false
  - scope:
      path: ""
      type: team
    values:
      job-title:
      image:
      email:
      social:
url: https://www.we-are-novel.com
description:
  A premium audio content company. Whether it’s compelling journalism,
  powerful podcasts or innovative branded content, we tell stories in sound that make
  people listen.
permalink: pretty
exclude:
  - package.json
  - config.codekit3
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - ".gitignore"
  - assets/scss
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll/imgix
include:
  - _redirects
company: Novel Ltd
email: info@nove.audio
analytics: UA-148099552-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %Y"
future: true
social:
  twitter: https://twitter.com/we_are_novel_
compress_html:
  comments:
    - "<!-- "
    - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 12
  limit: 0
  permalink: "/page/:num/"
  title: ":title"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
imgix:
  source: thisisnovel-beta.imgix.net
